# File: /home/maarten/multi_persona_chatbot/src/multipersona_chat_app/config/settings.yaml
- name: "Default Setting"
  description: "A standard conversation environment."
- name: "Intimate Setting"
  description: "Nestled in Japan's mountains, a serene resort beckoned under starry skies. Steaming hot springs and intimate mixed baths awaited, where guests in yukata robes strolled freely amidst cedar groves kissed by sunlight. Private rooms with tatami mats offered secluded escapes, each equipped with sake sets for quiet sipping. The uncrowded atmosphere allowed for peaceful reflections, making it an idyllic retreat amidst nature's splendor."
- name: "Formal Setting"
  description: "A professional and respectful environment."
