# File: /home/maarten/multi_persona_chatbot/src/multipersona_chat_app/config/settings.yaml
- name: "Default Setting"
  description: "A standard conversation environment."
- name: "Intimate Setting"
  description: "In the heart of Japan's mountains, a secluded resort beckoned with promises of serenity and hidden pleasures. Underneath star-studded skies, steaming hot springs and intimate mixed baths awaited, where guests in yukata robes strolled freely, their skin kissed by warm sunlight filtering through cedar groves. Waterfalls whispered secrets as nature bared its splendor - a haven for those seeking solace, connection, or perhaps something more, amidst the emerald embrace of ancient forests."
- name: "Formal Setting"
  description: "A professional and respectful environment."
